### ISSUE TITLE
CrossCompile problem for LibreELEC

### ISSUE THREAD

**Issue by piotrekcrash** [astrada/ocamlfuse#10]
Hi,

I'm using Your project on my Ubuntu machine and I planned to migrate this to Linux-based TV-Box with LibreELEC system.

I successfully compiled ocaml and cmalidl but when I try to compile ocamlfuse I receive this error:

`Fuse_bindings_stubs.o: file not recognized: File format is ambiguous
Fuse_bindings_stubs.o: matching formats: elf32-little elf64-little
collect2: error: ld returned 1 exit status`

Maybe You have some idea what I'm doing wrong?
Full log: [pastebin](https://pastebin.com/dpghFqEZ)

Regards

**Comment by astrada** [comment]
> Maybe You have some idea what I'm doing wrong?

I'm sorry but I don't have any experience with cross compilation.

**Comment by piotrekcrash** [comment]
You have right I'm new.  I wrongly compiled ocaml not cross compile for my target platform.  Now I'm changing configuration parametrs to cross compile it for target and then I'll try to compile ocamlfu
