### ISSUE TITLE
dune-private-libs.stdune required with dune 2.6.1

### ISSUE THREAD

**Issue by olafhering** [astrada/ocamlfuse#15]
When 5b5d03cf091b02f99ab01c5f866c62d48cc05f40 building with `dune` version 2.6.1, this change is required:
````bash
sed -i 's@dune.configurator@& dune-private-libs.stdune@' lib/config/dune
````

**Comment by astrada** [comment]
Thanks, but if you can upgrade to 707767e you won't need that fix.

**Comment by olafhering** [comment]
I was building the wrong git revision.
