### ISSUE TITLE
Unable to compile on Gentoo Linux

### ISSUE THREAD

**Issue by amclellan** [astrada/ocamlfuse#19]
I have an issue building ocamlfuse. I am using Gentoo Linux and there is no recent ebuild, so I am attempting a compile from source. When I issue the command "make" I get this message.

merlin ~/ocaml/ocamlfuse-2.7.1_cvs7 # make
File "lib/config/dune", line 3, characters 12-29:
3 |  (libraries dune.configurator))
                ^^^^^^^^^^^^^^^^^
Error: Library "dune.configurator" not found.
Hint: try: dune external-lib-deps --missing @install
make: *** [Makefile:3: build] Error 1

My system is:
Gentoo Linux Linux 5.4.66
fuse-3.9.1
ocaml-4.09.0
camlidl-1.05
dune-2.1.0

Have I an issue with ocamlfuse, my machine or my knowledge?

Please advise.

Many thanks,

Antony

**Comment by astrada** [comment]
Developing in OCaml is easier if you use [opam](http://opam.ocaml.org/), so you can easily install all the dependencies.

**Comment by amclellan** [comment]
Thank you for the advice to use opam; I am much further forward.

My system is now:

Gentoo Linux Linux 5.4.66
fuse-2.9.9
opam-2.0.7

Opam has installed the ocamlfuse dependences.

Now when I issue the command "opam install ocamlfuse" I get a different error:

[WARNING] Running as root is not recommended
The following actions will be performed:
  - install ocamlfuse 2.7.1-cvs7

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[ocamlfuse.2.7.1-cvs7] found in cache

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[ERROR] The compilation of ocamlfuse failed at
        "/root/.opam/opam-init/hooks/sandbox.sh build dune build -p ocamlfuse
        -j 1".

#=== ERROR while compiling ocamlfuse.2.7.1-cvs7 ===============================#
# context     2.0.7 | linux/x86_64 | ocaml-system.4.11.1 | https://opam.ocaml.org#c8467d9a
# path        ~/.opam/default/.opam-switch/build/ocamlfuse.2.7.1-cvs7
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build -p ocamlfuse -j 1
# exit-code   1
# env-file    ~/.opam/log/ocamlfuse-23401-d2c37b.env
# output-file ~/.opam/log/ocamlfuse-23401-d2c37b.out
### output ###
# [...]
# -> stderr:
# run: /usr/bin/pkg-config --cflags fuse
# -> process exited with code 0
# -> stdout:
#  | -I/usr/include/fuse -D_FILE_OFFSET_BITS=64
# -> stderr:
# run: /usr/bin/pkg-config --libs fuse
# -> process exited with code 0
# -> stdout:
#  | -lfuse -pthread
# -> stderr:
# Error: Could not query camlidl lib path



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
+- The following actions failed
| - build ocamlfuse 2.7.1-cvs7
+-
- No changes have been performed

I seem much closer, extra advice would be most welcome.

Many thanks,

Antony

**Comment by amclellan** [comment]
blank

**Comment by amclellan** [comment]
Thanks to astrada. I now have ocamlfuse installed. I have moved on to google-drive-ocamlfuse.
