### ISSUE TITLE
Cannot run make command

### ISSUE THREAD

**Issue by tjustice86** [astrada/ocamlfuse#9]
After unpacking and cd'ing into lib I try to run make and get this error:

`camlidl -header  \
                         Fuse_bindings.idl
make: camlidl: Command not found
../OCamlMakefile:1008: recipe for target 'Fuse_bindings.mli' failed
make: *** [Fuse_bindings.mli] Error 127`

**Comment by astrada** [comment]
You are missing camlidl as dependency. If you have opam, `opam install camlidl` should do.
